import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { FOOD_CONCEPTS } from "../src/domain/concepts";

const ALIAS_NAMESPACE_UUID = "9a1f3c67-8793-4f35-a240-2a26d4f54469";

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function uuidBytes(value: string): Buffer {
  return Buffer.from(value.replaceAll("-", ""), "hex");
}

/** RFC 4122 version-5 UUID, used so a fresh seed creates stable alias IDs. */
function uuidV5(name: string): string {
  const digest = createHash("sha1")
    .update(uuidBytes(ALIAS_NAMESPACE_UUID))
    .update(name, "utf8")
    .digest()
    .subarray(0, 16);
  digest[6] = (digest[6] & 0x0f) | 0x50;
  digest[8] = (digest[8] & 0x3f) | 0x80;
  const hex = digest.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

type GlobalAlias = Readonly<{
  foodConceptId: string;
  alias: string;
  normalizedAlias: string;
}>;

function globalAliases(): GlobalAlias[] {
  const aliases = new Map<string, GlobalAlias>();

  for (const concept of FOOD_CONCEPTS) {
    for (const alias of [concept.id, concept.name, ...concept.aliases]) {
      // This mirrors the generated normalized_alias expression in the schema.
      const normalizedAlias = alias.trim().toLocaleLowerCase("en-US");
      const existing = aliases.get(normalizedAlias);
      if (existing && existing.foodConceptId !== concept.id) {
        throw new Error(
          `Database alias collision: ${JSON.stringify(alias)} maps to both ${existing.foodConceptId} and ${concept.id}.`,
        );
      }
      aliases.set(normalizedAlias, {
        foodConceptId: concept.id,
        alias: alias.trim(),
        normalizedAlias,
      });
    }
  }

  return [...aliases.values()].sort(
    (left, right) =>
      left.normalizedAlias.localeCompare(right.normalizedAlias, "en-US") ||
      left.foodConceptId.localeCompare(right.foodConceptId, "en-US"),
  );
}

function valueRows(rows: readonly string[]): string {
  return rows.map((row) => `  (${row})`).join(",\n");
}

export function generateFoodConceptSeedSql(): string {
  const concepts = [...FOOD_CONCEPTS].sort((left, right) =>
    left.id.localeCompare(right.id, "en-US"),
  );
  const aliases = globalAliases();

  return [
    "-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.",
    "-- Global concepts and aliases are curated source data, not tenant data.",
    "begin;",
    "",
    "insert into public.food_concepts (id, canonical_name, category, is_active)",
    "values",
    valueRows(
      concepts.map(
        (concept) =>
          `${sqlText(concept.id)}, ${sqlText(concept.name)}, ${sqlText(concept.category)}, true`,
      ),
    ),
    "on conflict (id) do update",
    "set canonical_name = excluded.canonical_name,",
    "    category = excluded.category,",
    "    is_active = true",
    "where (food_concepts.canonical_name, food_concepts.category, food_concepts.is_active)",
    "  is distinct from (excluded.canonical_name, excluded.category, excluded.is_active);",
    "",
    "insert into public.food_aliases",
    "  (id, scope, household_id, food_concept_id, alias, created_by)",
    "values",
    valueRows(
      aliases.map(
        ({ foodConceptId, alias, normalizedAlias }) =>
          `${sqlText(uuidV5(`global:${normalizedAlias}`))}::uuid, 'global'::public.food_alias_scope, null, ${sqlText(foodConceptId)}, ${sqlText(alias)}, null`,
      ),
    ),
    "on conflict (normalized_alias) where scope = 'global' do update",
    "set food_concept_id = excluded.food_concept_id,",
    "    alias = excluded.alias",
    "where (food_aliases.food_concept_id, food_aliases.alias)",
    "  is distinct from (excluded.food_concept_id, excluded.alias);",
    "",
    "commit;",
    "",
  ].join("\n");
}

const outputFlagIndex = process.argv.indexOf("--output");
const outputArgument =
  outputFlagIndex === -1 ? null : process.argv[outputFlagIndex + 1];

if (outputFlagIndex >= 0 && !outputArgument) {
  throw new Error("--output requires a file path.");
}

const sql = generateFoodConceptSeedSql();
if (outputArgument) {
  await writeFile(path.resolve(process.cwd(), outputArgument), sql, "utf8");
} else {
  process.stdout.write(sql);
}
