import { describe, expect, it } from "vitest";
import type { Recipe } from "../src/contracts/domain";
import {
  generateReviewedRecipeImportSql,
  RecipeImportError,
} from "./lib/recipe-import-sql";

function reviewedRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return {
    id: "reviewed-rice",
    slug: "reviewed-rice",
    title: "Editor's Reviewed Rice",
    description: "An artificial reviewed fixture used only for SQL generator tests.",
    servings: 2,
    totalMinutes: 25,
    mealTypes: ["dinner"],
    cuisines: ["Test Kitchen"],
    dietaryTags: ["vegetarian"],
    ingredients: [
      {
        id: "rice",
        foodConceptId: "rice",
        name: "rice",
        amount: 1,
        unit: "cup",
        display: "1 cup rice",
        required: true,
        acceptedForms: ["dried"],
      },
      {
        id: "salt",
        foodConceptId: "salt",
        name: "salt",
        amount: 0.5,
        unit: "tsp",
        display: "1/2 teaspoon salt",
        required: true,
        acceptedForms: ["dried", "unspecified"],
      },
    ],
    steps: ["Combine the rice and salt in a pot.", "Cook the rice until tender."],
    rights: {
      owner: "Foodtopia",
      author: "Test Fixture Author",
      reviewer: "Test Fixture Reviewer",
      reviewedAt: "2026-08-13",
      status: "reviewed",
    },
    ...overrides,
  };
}

describe("reviewed recipe SQL import generation", () => {
  it("emits deterministic transactional upserts and stale-row cleanup", () => {
    const fixture = reviewedRecipe();
    const sql = generateReviewedRecipeImportSql([fixture]);

    expect(generateReviewedRecipeImportSql([fixture])).toBe(sql);
    expect(sql).toMatch(/^-- Generated by /);
    expect(sql).toContain("\nbegin;\n");
    expect(sql).toContain("insert into public.recipes");
    expect(sql).toContain("'published'::public.recipe_visibility");
    expect(sql).toContain("'reviewed'::public.recipe_review_status");
    expect(sql).toContain("'Test Fixture Reviewer'");
    expect(sql).toContain("'2026-08-13'::date");
    expect(sql).toContain("Editor''s Reviewed Rice");
    expect(sql).toContain("on conflict (id) do update");
    expect(sql).toContain("delete from public.recipe_ingredients as existing");
    expect(sql).toContain("insert into public.recipe_ingredients");
    expect(sql).toContain("on conflict (recipe_id, id) do update");
    expect(sql).toContain("array['dried', 'unspecified']::public.food_form[]");
    expect(sql).toMatch(/commit;\n$/);
  });

  it("sorts recipes by stable ID regardless of input order", () => {
    const first = reviewedRecipe({ id: "a-recipe", slug: "a-recipe" });
    const second = reviewedRecipe({ id: "b-recipe", slug: "b-recipe" });

    expect(generateReviewedRecipeImportSql([second, first])).toBe(
      generateReviewedRecipeImportSql([first, second]),
    );
  });

  it("never turns draft content into published content", () => {
    const draft = reviewedRecipe({
      rights: {
        owner: "Foodtopia",
        author: "Test Fixture Author",
        reviewer: null,
        reviewedAt: null,
        status: "draft",
      },
    });

    expect(() => generateReviewedRecipeImportSql([draft])).toThrow(
      RecipeImportError,
    );
  });

  it("rejects reviewed status without meaningful reviewer metadata", () => {
    const invalid = reviewedRecipe({
      rights: {
        owner: "Foodtopia",
        author: "Test Fixture Author",
        reviewer: "   ",
        reviewedAt: "2026-08-13",
        status: "reviewed",
      },
    });

    expect(() => generateReviewedRecipeImportSql([invalid])).toThrow(
      /nonblank reviewer/,
    );
  });

  it("casts nullable numeric amounts for a type-safe desired-row CTE", () => {
    const fixture = reviewedRecipe({
      ingredients: reviewedRecipe().ingredients.map((ingredient) => ({
        ...ingredient,
        amount: null,
        unit: null,
        display: `${ingredient.name}, as needed`,
      })),
    });

    expect(generateReviewedRecipeImportSql([fixture])).toContain(
      "null::numeric, null",
    );
  });
});
