import { describe, expect, it } from "vitest";
import type { Recipe } from "../src/contracts/domain";
import {
  generatePublicRecipeImportSql,
  RecipeImportError,
} from "./lib/recipe-import-sql";

function reviewedRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return {
    id: "reviewed-rice",
    slug: "reviewed-rice",
    title: "Editor's Reviewed Rice",
    description: "An artificial reviewed fixture used only for SQL generator tests.",
    servings: 2,
    totalMinutes: 25,
    mealTypes: ["dinner"],
    cuisines: ["Test Kitchen"],
    dietaryTags: ["vegetarian"],
    ingredients: [
      {
        id: "rice",
        foodConceptId: "rice",
        name: "rice",
        amount: 1,
        unit: "cup",
        display: "1 cup rice",
        required: true,
        acceptedForms: ["dried"],
      },
      {
        id: "salt",
        foodConceptId: "salt",
        name: "salt",
        amount: 0.5,
        unit: "tsp",
        display: "1/2 teaspoon salt",
        required: true,
        acceptedForms: ["dried", "unspecified"],
      },
    ],
    steps: ["Combine the rice and salt in a pot.", "Cook the rice until tender."],
    rights: {
      owner: "Foodtopia",
      author: "Test Fixture Author",
      reviewer: "Test Fixture Reviewer",
      reviewedAt: "2026-08-13",
      status: "reviewed",
    },
    ...overrides,
  };
}

describe("public recipe SQL import generation", () => {
  it("emits deterministic transactional upserts and stale-row cleanup", () => {
    const fixture = reviewedRecipe();
    const sql = generatePublicRecipeImportSql([fixture]);

    expect(generatePublicRecipeImportSql([fixture])).toBe(sql);
    expect(sql).toMatch(/^-- Generated by /);
    expect(sql).toContain("\nbegin;\n");
    expect(sql).toContain("insert into public.recipes");
    expect(sql).toContain("Public recipe import ID collides with a household recipe.");
    expect(sql).toContain("visibility = 'household' or household_id is not null");
    expect(sql.indexOf("Public recipe import ID collides")).toBeLessThan(
      sql.indexOf("insert into public.recipes"),
    );
    expect(sql).toContain("'published'::public.recipe_visibility");
    expect(sql).toContain("'reviewed'::public.recipe_review_status");
    expect(sql).toContain("'Test Fixture Reviewer'");
    expect(sql).toContain("'2026-08-13'::date");
    expect(sql).toContain("Editor''s Reviewed Rice");
    expect(sql).toContain("on conflict (id) do update");
    expect(sql).toContain("delete from public.recipe_ingredients as existing");
    expect(sql).toContain("insert into public.recipe_ingredients");
    expect(sql).toContain("on conflict (recipe_id, id) do update");
    expect(sql).toContain("array['dried', 'unspecified']::public.food_form[]");
    expect(sql).toMatch(/commit;\n$/);
  });

  it("sorts recipes and the private-ID collision guard deterministically", () => {
    const first = reviewedRecipe({ id: "a-recipe", slug: "a-recipe" });
    const second = reviewedRecipe({ id: "b-recipe", slug: "b-recipe" });

    const sql = generatePublicRecipeImportSql([second, first]);
    expect(sql).toBe(generatePublicRecipeImportSql([first, second]));
    expect(sql).toContain("where id in ('a-recipe', 'b-recipe')");
  });

  it("publishes initial-seed content without synthetic review metadata", () => {
    const seeded = reviewedRecipe({
      id: "seeded-rice",
      slug: "seeded-rice",
      rights: {
        owner: "Foodtopia",
        author: "Foodtopia Initial Catalog",
        reviewer: null,
        reviewedAt: null,
        status: "seeded",
      },
    });

    const sql = generatePublicRecipeImportSql([seeded]);
    expect(sql).toContain("'seeded'::public.recipe_review_status");
    expect(sql).toContain("null, null::date, 'seeded'");
  });

  it("rejects seeded content that claims review metadata", () => {
    const seeded = reviewedRecipe({
      rights: {
        owner: "Foodtopia",
        author: "Foodtopia Initial Catalog",
        reviewer: "Not a real review",
        reviewedAt: "2026-08-13",
        status: "seeded",
      },
    });

    expect(() => generatePublicRecipeImportSql([seeded])).toThrow(
      /must not claim a reviewer/,
    );
  });

  it("never turns draft content into published content", () => {
    const draft = reviewedRecipe({
      rights: {
        owner: "Foodtopia",
        author: "Test Fixture Author",
        reviewer: null,
        reviewedAt: null,
        status: "draft",
      },
    });

    expect(() => generatePublicRecipeImportSql([draft])).toThrow(
      RecipeImportError,
    );
  });

  it("rejects reviewed status without meaningful reviewer metadata", () => {
    const invalid = reviewedRecipe({
      rights: {
        owner: "Foodtopia",
        author: "Test Fixture Author",
        reviewer: "   ",
        reviewedAt: "2026-08-13",
        status: "reviewed",
      },
    });

    expect(() => generatePublicRecipeImportSql([invalid])).toThrow(
      /nonblank reviewer/,
    );
  });

  it("rejects reviewer metadata that cannot fit the database", () => {
    const invalid = reviewedRecipe({
      rights: {
        ...reviewedRecipe().rights,
        reviewer: "r".repeat(161),
      },
    });

    expect(() => generatePublicRecipeImportSql([invalid])).toThrow(
      /exceeds 160 characters/,
    );
  });

  it("casts nullable numeric amounts for a type-safe desired-row CTE", () => {
    const fixture = reviewedRecipe({
      ingredients: reviewedRecipe().ingredients.map((ingredient) => ({
        ...ingredient,
        amount: null,
        unit: null,
        display: `${ingredient.name}, as needed`,
      })),
    });

    expect(generatePublicRecipeImportSql([fixture])).toContain(
      "null::numeric, null",
    );
  });
});
